## Datasource Properties

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/opentxt_notesapp
    username: root
    password: password

## Hibernate Properties
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update

        show_sql: true
        format_sql: true