
## Eureka Server Configuration
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

## Datasource Properties
spring:
## Uncomment the following block to switch to h2 database
  profiles:
    active: ${PROFILE:default}
  datasource:
    url: jdbc:mysql://localhost:3306/opentxt_notesapp
    username: root
    password: password

## Hibernate Properties
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update

        show_sql: true
        format_sql: true

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always