## Datasource Properties



spring:
  ## Uncomment the following block to switch to h2 database
  #  profiles:
  #    active: h2
  datasource:
    url: jdbc:mysql://localhost:3306/opentxt_notesapp
    username: root
    password: password

  ## Hibernate Properties
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update

        show_sql: true
        format_sql: true

eureka:
  instance:
    hostname: localhost
    ip-address: 127.0.0.1
    prefer-ip-address: true
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/


resilience4j:
  circuitbreaker:
    instances:
        notesClient:
            registerHealthIndicator: true
            slidingWindowSize: 10
            minimumNumberOfCalls: 5
            failureRateThreshold: 50
            waitDurationInOpenState: 5s
            permittedNumberOfCallsInHalfOpenState: 2
            slidingWindowType: COUNT_BASED
            automaticTransitionFromOpenToHalfOpenEnabled: true