

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
        - id: notes-service
          uri: lb://notes-service
          predicates:
            - Path=/api/notes/**
eureka:
  instance:
    hostname: localhost
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/
    ip-address: 127.0.0.1
    prefer-ip-address: true